version: '3.7'

services:

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: bike-commerce
      MYSQL_USER: bike
      MYSQL_PASSWORD: commerce
    volumes:
      - ./import:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
