version: '3.7'

services:

  bike-commerce:
    image: bike-commerce:latest
    ports:
      - "8080:8080"
    restart: on-failure
    build:
      context: ./

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: bike-commerce
      MYSQL_USER: bike
      MYSQL_PASSWORD: commerce
    volumes:
      - ./import:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
